#! /bin/sh

### CyberSpark.net monitoring and cyberdetection software

### BEGIN INIT INFO
### CyberSpark.net monitoring services
# Provides:		cybersparkd
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start: 2 3 4 5
# Default-Stop:  0 1 6
# Short-Description:	CyberSpark.net agent
# Description:	CyberSpark monitoring agent
### 
### END INIT INFO

. /lib/lsb/init-functions
# The next line failed in Ubuntu 18.04 LTS
# . /etc/default/rcS

set -e

CSPATH="/usr/local/cyberspark"
ID=`cat $CSPATH/cyberspark.id.txt`
INITDPATH="/etc/init.d"
DESCRIPTION="CyberSpark service"
STARTUPMSGFILE="important_startup_message.txt"

    
case "$1" in
  start)
    ## After forced power-off, PID and NEXT files still exist. Try to clean up.
    if test -f "$CSPATH/$ID.pid"
    then
      PID=`cat $CSPATH/$ID.pid`
      # see if any process is running with the indicated PID
      RUNNING=`ps -ef | grep $PID`
      case "$RUNNING" in
        *cyberspark*) 
          echo "$DESCRIPTION is running as process $PID."
        ;;
        *) 
          log_daemon_msg "$DESCRIPTION (process $PID) mentioned in $CSPATH/$ID.pid is not running."
          log_daemon_msg "The server may be recovering from a power failure or forced shutdown."
          log_daemon_msg "This script will now remove all .pid, .next and .url files and attempt to start Cyberspark."
          rm -f $CSPATH/*.pid
          rm -f $CSPATH/*.next
          rm -f $CSPATH/*.url
          date -R  >> $CSPATH/$STARTUPMSGFILE
          echo "The server $ID may be recovering from a power failure or forced shutdown." >> $CSPATH/$STARTUPMSGFILE
          echo "Cleanup has been performed and '$DESCRIPTION' is being started." >> $CSPATH/$STARTUPMSGFILE
        ;;
      esac
    fi
    # If PID file still exists, then warn user to run 'stop' or to delete the files and processes
    if test -f "$CSPATH/$ID.pid"; then
      log_daemon_msg "$DESCRIPTION - maybe running already? $CSPATH/$ID.pid exists."
      log_daemon_msg "$DESCRIPTION - to restart, run 'stop' then 'start' separately."
      log_end_msg 1
    fi
    log_daemon_msg "Starting $DESCRIPTION $ID" "cybersparkd"
    CSOPTIONS="$CSPATH/cybersparkd.php --id $ID --daemon"
    if start-stop-daemon --start --quiet --oknodo --background --pidfile "$CSPATH/$ID.pid" --chdir "$CSPATH" --exec /usr/bin/php -- $CSOPTIONS; then
      log_end_msg 0
    else
      log_end_msg 1
    fi
    ;;
  stop)
    log_daemon_msg "Stopping $DESCRIPTION $ID" "cybersparkd"
    CSOPTIONS="$CSPATH/cybersparkd.php --id $ID --daemon"
    if start-stop-daemon --stop --quiet --oknodo --pidfile "$CSPATH/$ID.pid" --chdir "$CSPATH"; then
      log_end_msg 0
    else
      log_end_msg 1
    fi
    ;;
  status)
    ## Report status of service.
    if test -f "$CSPATH/$ID.pid"
    then
      PID=`cat $CSPATH/$ID.pid`
      # see if any process is running with the indicated PID
      RUNNING=`ps -ef | grep $PID`
      COUNT=0
      case "$RUNNING" in
        *cyberspark*) 
          echo "$DESCRIPTION is running as process $PID"
        ;;
        *) 
          echo "$DESCRIPTION (process $PID) mentioned in $CSPATH/$ID.pid should be running but is not."
       ;;
      esac
      # look at sniffers (child processes of the cybersparkd daemon)
      for F in $CSPATH/$ID-*.pid
      do
        PID=`cat $F`
        RUNNING=`ps -ef | grep $PID`
        CSNAME=$( echo $F | sed "s|$CSPATH/||" )
        CSNAME=$( echo $CSNAME | sed "s|.pid||" )
       case "$RUNNING" in
          *cyberspark*) 
            echo "  $CSNAME is running as process $PID."
          ;;
          *) 
            echo "  Daemon $CSNAME (process $PID) mentioned in $CSPATH/$ID.pid should be running but is not."
          ;;
        esac
      done
    else
      echo "$DESCRIPTION is not running. (No PID file was found for this service.)"
      exit 1
    fi
    ;;
  *)
    log_action_msg "Usage: service cyberspark {start|stop|status}"
    log_action_msg " or"
    log_action_msg "Usage: $INITDPATH/cyberspark {start|stop|status}"
    exit 1
    ;;
esac

exit 0
